arch:     s390x
os:       linux
dist:     bionic
language: cpp
sudo:     required
env:      |
          CFLAGS="-O3 -std=c99 -pedantic -Wextra -Wextra -Werror"
          CXXFLAGS="-O3 -std=c++11 -pedantic -Wextra -Wextra -Werror"
compiler:
        - gcc
        - clang

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install cmake libjson-c-dev

script:
        - mkdir build && cd build
        - cmake -DENABLE_TEST=ON ..
        - make
