arch:     s390x
os:       linux
dist:     noble
language: c
sudo:     required

compiler:
        - gcc
        - clang

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y cmake libjson-c-dev

before_script:
        - git clone https://github.com/openssl/openssl.git
        - pushd openssl
        - git checkout --track origin/openssl-3.5
        - ./config -w 2> >(tee)
        - make -s -j4 2> >(tee)
        - export OPENSSL_DIR=$(pwd)
        - export PATH=${OPENSSL_DIR}/apps/:${PATH}
        - export LD_LIBRARY_PATH=${OPENSSL_DIR}:${LD_LIBRARY_PATH}
        - popd

script:
        - set -o pipefail
        - cmake -B build -S . -DCMAKE_INCLUDE_PATH=${OPENSSL_DIR} -DCMAKE_LIBRARY_PATH=${OPENSSL_DIR} 2> >(tee)
        - cmake --build build --target zpc 2> >(tee)
