arch:     s390x
os:       linux
dist:     jammy
language: cpp
sudo:     required
env:      |
          CFLAGS="-O3 -Wextra -Wextra -Werror"
          CXXFLAGS="-O3 -Wextra -Wextra -Werror"
compiler:
        - gcc
        - clang

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install cmake libjson-c-dev

script:
        - set -o pipefail
        - mkdir build 2> >(tee) && cd build 2> >(tee)
        - cmake -DBUILD_TEST=ON .. 2> >(tee)
        - make 2> >(tee)
